wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 8
comparison_loss_factor:
  desc: null
  value: 1.0192039064061555
comparison_loss_fn:
  desc: null
  value: mse_loss
dir_name:
  desc: null
  value: ../data_source/LONDON_DATASET
dis_dropout:
  desc: null
  value: 0.20551347518372506
gen_dropout:
  desc: null
  value: 0.574320218824403
lr:
  desc: null
  value: 8.011955528707484e-05
num_epochs:
  desc: null
  value: 75
save_rate:
  desc: null
  value: 101
task:
  desc: null
  value: reg
test_metric:
  desc: null
  value: mse_loss
test_size:
  desc: null
  value: 0.2
wandb:
  desc: null
  value: 1
