wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 5
channels:
  desc: null
  value:
  - NDVI
  - NDBI
  - NDWI
classes:
  desc: null
  value:
  - LSTN
comparison_loss_factor:
  desc: null
  value: 1.2
comparison_loss_fn:
  desc: null
  value: mse_loss
data_dir:
  desc: null
  value: /content/drive/My Drive/LONDON_DATASET
dis_dropout:
  desc: null
  value: 0.4
gen_dropout:
  desc: null
  value: 0.4
loss_parameters:
  desc: null
  value: null
lr:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 20
random_state:
  desc: null
  value: null
save_rate:
  desc: null
  value: 1
task:
  desc: null
  value: reg
test_metric:
  desc: null
  value: mse_loss
test_parameters:
  desc: null
  value: null
test_size:
  desc: null
  value: 0.2
train_size:
  desc: null
  value: null
wandb:
  desc: null
  value: 1
